<html>
    <head>

    </head>
    <body>

        <h1>
            Porque eu quero entrar na eliti
        </h1>
        <h3>Nome:Gabriel Libanio Souza de Almeida conceição
            idade:15 anos
        </h3>
        
        <p>Bom a eliti vai trazer novas experiência para minha vida e por isso eu gostaria de entrar
            na eliti, mais tambem a eliti vai entrar na minha vida como um meio de trabalho e de evolução
            afinal agente esta ne uma era de computação,programação e tecnologia.
        </p>

        <p>E por isso eu gostaria muito de entrar pra eliti. </p>
    </body>
</html>
